//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AukcijaKlijent.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AukcijaWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eksponat", Namespace="http://schemas.datacontract.org/2004/07/AukcijaWCF")]
    [System.SerializableAttribute()]
    public partial class Eksponat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AukcijaKlijent.ServiceReference1.KlijentAukcije[] klijentiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AukcijaKlijent.ServiceReference1.KlijentAukcije najveciPonudjacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AukcijaKlijent.ServiceReference1.KlijentAukcije[] klijenti {
            get {
                return this.klijentiField;
            }
            set {
                if ((object.ReferenceEquals(this.klijentiField, value) != true)) {
                    this.klijentiField = value;
                    this.RaisePropertyChanged("klijenti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AukcijaKlijent.ServiceReference1.KlijentAukcije najveciPonudjac {
            get {
                return this.najveciPonudjacField;
            }
            set {
                if ((object.ReferenceEquals(this.najveciPonudjacField, value) != true)) {
                    this.najveciPonudjacField = value;
                    this.RaisePropertyChanged("najveciPonudjac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KlijentAukcije", Namespace="http://schemas.datacontract.org/2004/07/AukcijaWCF")]
    [System.SerializableAttribute()]
    public partial class KlijentAukcije : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid KlijentAukcijeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid KlijentAukcijeId {
            get {
                return this.KlijentAukcijeIdField;
            }
            set {
                if ((this.KlijentAukcijeIdField.Equals(value) != true)) {
                    this.KlijentAukcijeIdField = value;
                    this.RaisePropertyChanged("KlijentAukcijeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAukcija")]
    public interface IAukcija {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/GetData", ReplyAction="http://tempuri.org/IAukcija/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/GetData", ReplyAction="http://tempuri.org/IAukcija/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAukcija/GetDataUsingDataContractResponse")]
        AukcijaKlijent.ServiceReference1.CompositeType GetDataUsingDataContract(AukcijaKlijent.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAukcija/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(AukcijaKlijent.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiEksponat", ReplyAction="http://tempuri.org/IAukcija/vratiEksponatResponse")]
        AukcijaKlijent.ServiceReference1.Eksponat vratiEksponat(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiEksponat", ReplyAction="http://tempuri.org/IAukcija/vratiEksponatResponse")]
        System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.Eksponat> vratiEksponatAsync(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiSveEksponate", ReplyAction="http://tempuri.org/IAukcija/vratiSveEksponateResponse")]
        AukcijaKlijent.ServiceReference1.Eksponat[] vratiSveEksponate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiSveEksponate", ReplyAction="http://tempuri.org/IAukcija/vratiSveEksponateResponse")]
        System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.Eksponat[]> vratiSveEksponateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/prijaviLicitaciju", ReplyAction="http://tempuri.org/IAukcija/prijaviLicitacijuResponse")]
        void prijaviLicitaciju(string idEksponata, string ime, string prezime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/prijaviLicitaciju", ReplyAction="http://tempuri.org/IAukcija/prijaviLicitacijuResponse")]
        System.Threading.Tasks.Task prijaviLicitacijuAsync(string idEksponata, string ime, string prezime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiKlijentaAukcije", ReplyAction="http://tempuri.org/IAukcija/vratiKlijentaAukcijeResponse")]
        AukcijaKlijent.ServiceReference1.KlijentAukcije vratiKlijentaAukcije(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiKlijentaAukcije", ReplyAction="http://tempuri.org/IAukcija/vratiKlijentaAukcijeResponse")]
        System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.KlijentAukcije> vratiKlijentaAukcijeAsync(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/odustaniOdLicitacije", ReplyAction="http://tempuri.org/IAukcija/odustaniOdLicitacijeResponse")]
        void odustaniOdLicitacije(string idEksponata, string klijentAukcijeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/odustaniOdLicitacije", ReplyAction="http://tempuri.org/IAukcija/odustaniOdLicitacijeResponse")]
        System.Threading.Tasks.Task odustaniOdLicitacijeAsync(string idEksponata, string klijentAukcijeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiCenu", ReplyAction="http://tempuri.org/IAukcija/vratiCenuResponse")]
        int vratiCenu(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiCenu", ReplyAction="http://tempuri.org/IAukcija/vratiCenuResponse")]
        System.Threading.Tasks.Task<int> vratiCenuAsync(string idEksponata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/povecajCenu", ReplyAction="http://tempuri.org/IAukcija/povecajCenuResponse")]
        void povecajCenu(string idEksponata, string ime, string prezime, int iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/povecajCenu", ReplyAction="http://tempuri.org/IAukcija/povecajCenuResponse")]
        System.Threading.Tasks.Task povecajCenuAsync(string idEksponata, string ime, string prezime, int iznos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiIdKlijenta", ReplyAction="http://tempuri.org/IAukcija/vratiIdKlijentaResponse")]
        string vratiIdKlijenta(string idEksponata, string ime, string prezime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAukcija/vratiIdKlijenta", ReplyAction="http://tempuri.org/IAukcija/vratiIdKlijentaResponse")]
        System.Threading.Tasks.Task<string> vratiIdKlijentaAsync(string idEksponata, string ime, string prezime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAukcijaChannel : AukcijaKlijent.ServiceReference1.IAukcija, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AukcijaClient : System.ServiceModel.ClientBase<AukcijaKlijent.ServiceReference1.IAukcija>, AukcijaKlijent.ServiceReference1.IAukcija {
        
        public AukcijaClient() {
        }
        
        public AukcijaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AukcijaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AukcijaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AukcijaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AukcijaKlijent.ServiceReference1.CompositeType GetDataUsingDataContract(AukcijaKlijent.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(AukcijaKlijent.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public AukcijaKlijent.ServiceReference1.Eksponat vratiEksponat(string idEksponata) {
            return base.Channel.vratiEksponat(idEksponata);
        }
        
        public System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.Eksponat> vratiEksponatAsync(string idEksponata) {
            return base.Channel.vratiEksponatAsync(idEksponata);
        }
        
        public AukcijaKlijent.ServiceReference1.Eksponat[] vratiSveEksponate() {
            return base.Channel.vratiSveEksponate();
        }
        
        public System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.Eksponat[]> vratiSveEksponateAsync() {
            return base.Channel.vratiSveEksponateAsync();
        }
        
        public void prijaviLicitaciju(string idEksponata, string ime, string prezime) {
            base.Channel.prijaviLicitaciju(idEksponata, ime, prezime);
        }
        
        public System.Threading.Tasks.Task prijaviLicitacijuAsync(string idEksponata, string ime, string prezime) {
            return base.Channel.prijaviLicitacijuAsync(idEksponata, ime, prezime);
        }
        
        public AukcijaKlijent.ServiceReference1.KlijentAukcije vratiKlijentaAukcije(string idEksponata) {
            return base.Channel.vratiKlijentaAukcije(idEksponata);
        }
        
        public System.Threading.Tasks.Task<AukcijaKlijent.ServiceReference1.KlijentAukcije> vratiKlijentaAukcijeAsync(string idEksponata) {
            return base.Channel.vratiKlijentaAukcijeAsync(idEksponata);
        }
        
        public void odustaniOdLicitacije(string idEksponata, string klijentAukcijeId) {
            base.Channel.odustaniOdLicitacije(idEksponata, klijentAukcijeId);
        }
        
        public System.Threading.Tasks.Task odustaniOdLicitacijeAsync(string idEksponata, string klijentAukcijeId) {
            return base.Channel.odustaniOdLicitacijeAsync(idEksponata, klijentAukcijeId);
        }
        
        public int vratiCenu(string idEksponata) {
            return base.Channel.vratiCenu(idEksponata);
        }
        
        public System.Threading.Tasks.Task<int> vratiCenuAsync(string idEksponata) {
            return base.Channel.vratiCenuAsync(idEksponata);
        }
        
        public void povecajCenu(string idEksponata, string ime, string prezime, int iznos) {
            base.Channel.povecajCenu(idEksponata, ime, prezime, iznos);
        }
        
        public System.Threading.Tasks.Task povecajCenuAsync(string idEksponata, string ime, string prezime, int iznos) {
            return base.Channel.povecajCenuAsync(idEksponata, ime, prezime, iznos);
        }
        
        public string vratiIdKlijenta(string idEksponata, string ime, string prezime) {
            return base.Channel.vratiIdKlijenta(idEksponata, ime, prezime);
        }
        
        public System.Threading.Tasks.Task<string> vratiIdKlijentaAsync(string idEksponata, string ime, string prezime) {
            return base.Channel.vratiIdKlijentaAsync(idEksponata, ime, prezime);
        }
    }
}
